language: node_js
node_js:
- v7
- v6
- v5
- v4
after_script: cat ./coverage/lcov.info | coveralls
env:
  global:
    secure: Yn2g0J2MU9xju1V9s6B6obEykyzFOzq9xD+0lh18rJaFARrthk+D/5C/ZvvMGKvHK8IRGcYnf/KWV5Yx8wJHVQd28iln99pht16pGuYj2mJF2jWNmxpn1jQiGlLrvJrbN9o5/jZhPXPTtdz5HbvNMQ9XkV5iPcLBiKa4ZWj17lR75fUPtvX9Ka33d3a9ZxwXpsZBpOy+GGosEKWtbUiSY417zyR/5IsueMKsFiyY1dwC3BRpmy9ClkYjPwdV5tlpHSFKj6OB1+idNg9t+vzJKQDXywH8DasvkFsUWksLOPuSl0n57HSDAHNTfqKtREVBCAFMxrjk0Zk9CsGxeIyG7TwDPoknznFNug0hHqBQCi1xsljOGzwyyISwdvwHHWzWL2RWLguYrZ7D9Xly6h7uXC9IFub4/j+ogyikSghrMmi883ZXSOpjb/1QCAelfst2FDLxl5k/iJNnTowJhPwI2GXe52v8VVHm75QTNdF6bKMzIh/wZj6PTI+X8qIvXglti9fdkRaR40nGs70sy/VXZzqRLR+ro3EuLgTnCSb3PenTc1J9XekjFa82tQpGlqT0AbnQCt9tlUQvmlRgDj46ulU39OER7/UbpgN2OXjsfy+tF2szmwO0VRzndGbF45fkNhcbKIxPK+d8lkJwLMRb8vUYlquYVtzqXwG2tMfJgho=
